# <b><span style='color:#F1A424'>AutoML - Regression - Advertisment Sales Prediction </span> </b>

### Disclaimer
The sample code (“Sample Code”) provided is not covered by any Teradata agreements. Please be aware that Teradata has no control over the model responses to such sample code and such response may vary. The use of the model by Teradata is strictly for demonstration purposes and does not constitute any form of certification or endorsement. The sample code is provided “AS IS” and any express or implied warranties, including the implied warranties of merchantability and fitness for a particular purpose, are disclaimed. In no event shall Teradata be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) sustained by you or a third party, however caused and on any theory of liability, whether in contract, strict liability, or tort arising in any way out of the use of this sample code, even if advised of the possibility of such damage.

## <b> Problem overview:</b>

**Dataset Used : Advertising Sales Dataset**

**Features**:

- `TV`: Advertising done on TV.
- `Radio`: Advertising done on Radio.
- `Newspapaer`: Advertising done on Newspaper.

**Target Variable**:

- `Sales`: The Sales received after advertisement.
    
**Objective**:

The primary objective is typically to build a model that can accurately predict sales received based on advertisement.

**Usecase**:

Here, we will use AutoML(Automated Machine Learning) functionality to automate the entire process of developing a predictive model. It will perform feature exploration, feature engineering, data preparation, model training and evaluation on dataset in auto run and at end we will get leaderboard containined different models along with their performance. Model will also have rank associated with them which indicates which is best performing model for given data followed by other models.

In [1]:
# Importing other important libraries
import getpass
from teradataml import create_context, display
from teradataml import TrainTestSplit

display.enable_ui = False

In [2]:
# Create the connection.
host = getpass.getpass("Host: ")
username = getpass.getpass("Username: ")
password = getpass.getpass("Password: ")

ctx = create_context(host=host, username=username, password=password)

## <b><span style='color:#F1A424'>| 1.</span> Loading Deployed Models - 'Advertising_top_5_models' </b>

### <b><span style='color:#F1A424'>| 1.1.</span> Loading Model </b>

In [3]:
# Creating AutoML object

aml=ctx.AutoML()

In [4]:
# Loading models

models_1 = aml.load('Advertising_top_5_models')

In [5]:
# Display loaded models

models_1

,RANK,MODEL_ID,FEATURE_SELECTION,MAE,MSE,MSLE,MAPE,MPE,RMSE,RMSLE,ME,R2,EV,MPD,MGD,DATA_TABLE,ADJUSTED_R2
0,1,GLM_0,rfe,1.234628,2.469862,0.010376,8.761338,-0.951111,1.571580,0.101862,3.098927,0.914547,0.914933,0.161364,0.011955,automl__sales_rfe_179270149295251,0.913445
1,2,GLM_1,pca,1.438264,3.416078,0.014386,10.106047,-0.161727,1.848264,0.119940,3.561602,0.881810,0.881940,0.222911,0.016911,automl__sales_pca_179266299282937,0.879508
2,3,SVM_0,rfe,1.477064,4.089348,0.017088,10.449712,0.951526,2.022214,0.130722,4.263786,0.858516,0.874411,0.267864,0.019928,automl__sales_rfe_179270149295251,0.856690
3,4,DECISIONFOREST_0,rfe,1.708021,4.451459,0.021828,13.179133,-2.083894,2.109848,0.147743,6.200000,0.845988,0.846016,0.313882,0.026088,automl__sales_rfe_179270149295251,0.844000
4,5,DECISIONFOREST_1,pca,1.794922,4.567683,0.022736,13.952043,-3.206682,2.137214,0.150786,5.746154,0.841967,0.842111,0.319895,0.026534,automl__sales_pca_179266299282937,0.838888

### <b><span style='color:#F1A424'>| 1.2.</span> Get Loaded Model Hyperparameters</b>

In [6]:
aml.model_hyperparameters(rank=1, use_loaded_models=True)

{'response_column': 'sales',
 'family': 'GAUSSIAN',
 'lambda1': 0.001,
 'alpha': 0.15,
 'learning_rate': 'constant',
 'initial_eta': 0.1,
 'momentum': 0.65,
 'iter_num_no_change': 10,
 'iter_max': 100,
 'batch_size': 50}

In [7]:
aml.model_hyperparameters(rank=5, use_loaded_models=True)

{'response_column': 'sales',
 'tree_type': 'Regression',
 'min_impurity': 0.1,
 'max_depth': 6,
 'min_node_size': 2,
 'num_trees': -1,
 'seed': 42}

### <b><span style='color:#F1A424'>| 1.3.</span> Loading Dataset</b>

In [8]:
### Loading Dataset for Prediction

ctx.load_example_data('teradataml','advertising')
df = ctx.DataFrame('advertising')

WARNING: Skipped loading table advertising since it already exists in the database.

In [9]:
# Display data

df

       radio  newspaper  sales
TV
218.5    5.4       27.4   17.2
149.7   35.6        6.0   17.3
8.4     27.2        2.1    5.7
220.3   49.0        3.2   24.7
255.4   26.9        5.5   19.8
38.2     3.7       13.8    7.6
239.9   41.5       18.5   23.2
227.2   15.8       49.9   19.8
43.1    26.7       35.1   10.1
187.9   17.2       17.9   19.7

### <b><span style='color:#F1A424'>| 1.4.</span> Generating Prediction & Performance Metrics</b>

In [10]:
# Generate prediction using some data rows and model rank

prediction = aml.predict(df, rank=1)

In [11]:
prediction

   automl_id  prediction  sales
0        122    6.379172    6.9
1        162   10.037211   11.9
2        202   11.031172   10.9
3         61   18.158953   19.6
4         80   24.781262   26.2
5        242   20.007485   19.4
6         99   18.838264   17.1
7         95   10.224476   10.5
8        101   23.749025   25.4
9         17    8.174587    5.3

In [12]:
# Generate performance metrics

performance_metric = aml.evaluate(df, rank=1)

In [13]:
performance_metric

############ result Output ############

       MAE       MSE     MSLE       MAPE       MPE      RMSE     RMSLE        ME       R2        EV       MPD       MGD
0  1.23877  2.708817  0.02179  11.331804 -3.707445  1.645848  0.147614  7.345068  0.90249  0.902499  0.221128  0.024124

In [14]:
# Generate prediction using data and model rank

prediction = aml.predict(df, rank=4)

In [15]:
prediction

   automl_id  prediction  confidence_lower  confidence_upper  sales
0        122    8.550000          8.550000          8.550000    6.9
1         80   24.533333         24.533333         24.533333   26.2
2        242   17.605000         17.605000         17.605000   19.4
3        101   24.533333         24.533333         24.533333   25.4
4        183   16.900000         16.900000         16.900000   18.0
5        221    9.958333          9.958333          9.958333   12.6
6         40   11.900000         11.900000         11.900000   10.4
7        120    4.683333          4.683333          4.683333    6.6
8         99   17.605000         17.605000         17.605000   17.1
9         95   10.900000         10.900000         10.900000   10.5

In [16]:
# Generate performance metrics

performance_metric = aml.evaluate(df, rank=4)

In [17]:
performance_metric

############ result Output ############

        MAE       MSE      MSLE      MAPE       MPE      RMSE     RMSLE   ME        R2        EV       MPD       MGD
0  1.127458  2.523328  0.015233  9.288666 -0.854033  1.588499  0.123423  6.2  0.909167  0.909784  0.188162  0.019185

## <b><span style='color:#F1A424'>| 2.</span> Loading Deployed Models - 'Advertising_mixed_models' </b>

### <b><span style='color:#F1A424'>| 2.1.</span> Loading Model </b>

In [18]:
# Loading models

models_2 = aml.load('Advertising_mixed_models')

In [19]:
models_2

,RANK,MODEL_ID,FEATURE_SELECTION,MAE,MSE,MSLE,MAPE,MPE,RMSE,RMSLE,ME,R2,EV,MPD,MGD,DATA_TABLE,ADJUSTED_R2
0,1,GLM_1,pca,1.438264,3.416078,0.014386,10.106047,-0.161727,1.848264,0.119940,3.561602,0.881810,0.881940,0.222911,0.016911,automl__sales_pca_179264772816673,0.879508
1,2,DECISIONFOREST_0,rfe,1.708021,4.451459,0.021828,13.179133,-2.083894,2.109848,0.147743,6.200000,0.845988,0.846016,0.313882,0.026088,automl__sales_rfe_179265852037920,0.844000
2,3,DECISIONFOREST_1,pca,1.794922,4.567683,0.022736,13.952043,-3.206682,2.137214,0.150786,5.746154,0.841967,0.842111,0.319895,0.026534,automl__sales_pca_179264772816673,0.838888

### <b><span style='color:#F1A424'>| 2.2.</span> Generating Prediction & Performance Metrics</b>

In [20]:
# Generate prediction using data and model rank

prediction = aml.predict(df, rank=2)

In [21]:
prediction

   automl_id  prediction  confidence_lower  confidence_upper  sales
0        183   16.900000         16.900000         16.900000   18.0
1         80   24.533333         24.533333         24.533333   26.2
2        242   17.605000         17.605000         17.605000   19.4
3        122    8.550000          8.550000          8.550000    6.9
4         61   17.605000         17.605000         17.605000   19.6
5        141   23.275000         23.275000         23.275000   23.7
6        101   24.533333         24.533333         24.533333   25.4
7         17    4.683333          4.683333          4.683333    5.3
8         99   17.605000         17.605000         17.605000   17.1
9         95   10.900000         10.900000         10.900000   10.5

In [22]:
# Generate performance metrics

performance_metric = aml.evaluate(df, rank=2)

In [23]:
performance_metric

############ result Output ############

        MAE       MSE      MSLE      MAPE       MPE      RMSE     RMSLE   ME        R2        EV       MPD       MGD
0  1.127458  2.523328  0.015233  9.288666 -0.854033  1.588499  0.123423  6.2  0.909167  0.909784  0.188162  0.019185

## <b><span style='color:#F1A424'>| 3.</span> Loading Deployed Models - 'Advertising_range_models' </b>

### <b><span style='color:#F1A424'>| 3.1.</span> Loading Model</b>

In [24]:
# Creating another AutoML object

obj=ctx.AutoML()

In [25]:
# Loading models

models_3 = obj.load('Advertising_range_models')

In [26]:
models_3

,RANK,MODEL_ID,FEATURE_SELECTION,MAE,MSE,MSLE,MAPE,MPE,RMSE,RMSLE,ME,R2,EV,MPD,MGD,DATA_TABLE,ADJUSTED_R2
0,1,GLM_1,pca,1.438264,3.416078,0.014386,10.106047,-0.161727,1.848264,0.119940,3.561602,0.881810,0.881940,0.222911,0.016911,automl__sales_pca_179265723434984,0.879508
1,2,SVM_0,rfe,1.477064,4.089348,0.017088,10.449712,0.951526,2.022214,0.130722,4.263786,0.858516,0.874411,0.267864,0.019928,automl__sales_rfe_179265103930063,0.856690
2,3,DECISIONFOREST_0,rfe,1.708021,4.451459,0.021828,13.179133,-2.083894,2.109848,0.147743,6.200000,0.845988,0.846016,0.313882,0.026088,automl__sales_rfe_179265103930063,0.844000
3,4,DECISIONFOREST_1,pca,1.794922,4.567683,0.022736,13.952043,-3.206682,2.137214,0.150786,5.746154,0.841967,0.842111,0.319895,0.026534,automl__sales_pca_179265723434984,0.838888
4,5,XGBOOST_1,pca,2.020398,6.938642,0.022857,12.836576,8.061041,2.634130,0.151187,7.126380,0.759936,0.854588,0.419577,0.027590,automl__sales_pca_179265723434984,0.755259
5,6,XGBOOST_0,rfe,2.130200,6.947554,0.029227,16.175565,-4.851764,2.635821,0.170958,6.861734,0.759627,0.760336,0.454441,0.033758,automl__sales_rfe_179265103930063,0.756526

### <b><span style='color:#F1A424'>| 3.2.</span> Generating Prediction & Performance Metrics</b>

In [27]:
# Generate prediction using data and model rank

prediction = obj.predict(df.iloc[:80], rank=1)

In [28]:
prediction

   automl_id  prediction  sales
0        626   12.934979   11.9
1        242    6.229998    7.6
2        402    9.581099   10.9
3        610   16.337857   16.7
4        274   11.439573   10.4
5         34    8.001874    5.5
6        570   10.029487   10.7
7        122    8.790110    8.0
8        530    9.373501   14.0
9        522   14.944864   15.3

In [29]:
# Generate performance metrics

performance_metric = obj.evaluate(df.iloc[:80], rank=1)

In [30]:
performance_metric

############ result Output ############

        MAE       MSE      MSLE       MAPE       MPE      RMSE     RMSLE        ME       R2        EV      MPD       MGD
0  1.301583  3.264574  0.043507  17.784016 -2.991984  1.806813  0.208583  5.881563  0.62697  0.638253  0.38369  0.052163

In [31]:
ctx.remove_context()

True